### ISSUE TITLE
Pagination in Tickets.ListAsync

### ISSUE THREAD

**Issue by martinavila69** [justeat/ZendeskApiClient#117]
Hi,
I execute 
     Dim t As Responses.IPagination(Of Models.Ticket)
     t = Await zdClient.Tickets.ListAsync
and it says that 400 tickets exist and I can access the first 100.

After that, I can not access the second, third, etc. pages (don't know how).

Could you please show me how?

Thanks in advance.
Martin

**Comment by slang25** [comment]
@martinavila69 disclaimer: I haven't used this library.

It looks like there is an overload for `ListAsync` that takes a `PagerParameters` object, which can be used like this:

```csharp
var retrievedTickets = (await _resource.ListAsync(new PagerParameters { Page = 1, PageSize = 5 })).ToArray();
```

[see here](https://github.com/justeat/ZendeskApiClient/blob/b04e5a6340c23ac9295714f35cf871ca4fc50c69/test/ZendeskApi.Client.Tests/Resources/TicketsResourceTests.cs#L47)

Let us know if this doesn't resolve your issue, and I'll let someone who knows what they are talking about answer 😃

**Comment by martinavila69** [comment]
Thank you @slang25!

It worked perfectly! Now I see the example in the test files.
