### ISSUE TITLE
New Ticket Creation by End Users Possible?

### ISSUE THREAD

**Issue by AaronW** [justeat/ZendeskApiClient#12]
Hello, I was wondering if it's currently possible to create new Tickets using end-user accounts within ZenDesk using this client?  The Tickets endpoint is only accessible to agents, end-users use "Requests" but I don't see it implemented in the API. Maybe I'm missing it though!

https://developer.zendesk.com/rest_api/docs/core/requests

**Comment by kate-r** [comment]
Hello,

I haven't implemented requests within the client so far. However, it does sound like something that would be useful.

If you like, you could implement requests in the client yourself and send me a pull request. Otherwise, I'll take a look when I get chance over the next few weeks.

Kate

**Comment by AaronW** [comment]
Kate,

Thanks for the speedy response! I'm working on implementing it and will send a pull request when I get it working.

**Comment by kate-r** [comment]
Hello,

There were issues with this on Zendesk's side last week. Give it another try and see if it works now.

Thanks for contributing :)

Kate

**Comment by carlospuk** [comment]
I believe that posting Requests is slightly different to posting Tickets in a few other ways - don't you need to:

*  Pass the *end-user*'s email address instead of the agents
* Append /token and your auth token
* Attach a comment field as a minimum.  I can't see a 'comment' field in your Request class?

I'll look into this myself too.

**Comment by kate-r** [comment]
Hi,

You can create a new instance of the client and pass in the end user's email and your api token. I can see that creating a new client for each time of request might be annoying/messy so appending /token is perhaps something that should be added.

As you say, the comment field does need to be set. Here's a test setting the comment field. https://github.com/justeat/ZendeskApiClient/blob/master/src/ZendeskApi.Acceptance/RequestSteps.cs#L34

We don't work with requests so any suggestions (or pull requests) for how the client can better support real-world Request user cases would be appreciated.

Kate

**Comment by carlospuk** [comment]
Weirdly, I didn't have a 'Comment' field in the model I downloaded from @AaronW 's fork.   I'm working my way through this, just battling ZenDesk on some auth failures but it's looking like @AaronW may have already done most of the work here.

**Comment by kate-r** [comment]
A few people have asked about requests so there's support for this now in the master of this in the current public nuget package (v1.0.82). https://github.com/justeat/ZendeskApiClient/blob/master/src/ZendeskApi.Client/Resources/RequestResource.cs

**Comment by carlospuk** [comment]
OK, it looks to me as though the ability to POST end-user requests is working just fine, although it also seems that one has to ensure the end user has been created in advance.

Creating new users seems easy enough, via client.Users.Post(new UserRequest() { Item = user });

But does your client currently support searching for an existing user by email address, to check if they exist before creating them?  i.e. GET /api/v2/users/search.json?query={query}

**Comment by kate-r** [comment]
You can use the search resource to do that. Take a look at this acceptance test:

Feature: https://github.com/justeat/ZendeskApiClient/blob/master/src/ZendeskApi.Acceptance/Search.feature#L24

Code behind : https://github.com/justeat/ZendeskApiClient/blob/master/src/ZendeskApi.Acceptance/SearchSteps.cs#L61

**Comment by carlospuk** [comment]
I think that this issue can be closed now.  I have successfully used the latest version of your client to post end-user Requests.  The key workflow is:

* Create the `User` first if they don't exist.
* Ensure that the User's `Verified` field is set to `True`.  
* When posting the `Request`, use a specially constructed ZeskClient, passing the `User` email address instead of the agents

Example code is below - feel free to share, or add to the ReadMe if that would be helpful.

    Request createEndUserRequest(string strEndUserName, string strEndUserEmail, string strSubject, string strDescription, string strOS, string customProductCode)
        {

            //  Create our client
            IZendeskClient client = new ZendeskClient(new Uri("https://yourcompany.zendesk.com/api/v2"), new ZendeskDefaultConfiguration("AGENT_LOGIN_EMAIL", "YOUR_TOKEN"));
            
            // Does the end user already exist?
            var searchUserResponse = client.Search.Find<User>(
                new ZendeskQuery<User>()
                .WithCustomFilter("email", strEndUserEmail)
            );

            long? userID = null;
            if (searchUserResponse.TotalCount == 0)
            {
                // Create the end user; be sure to add as 'verified' so we can post a Request on their behalf
                User usr = new User()
                {
                    Name = strEndUserName,
                    Email = strEndUserEmail,
                    Verified = true
                };

                var userResponse = client.Users.Post(new UserRequest() { Item = usr });
                userID = userResponse.Item.Id.Value;
            }
            else
                userID = searchUserResponse.Results.First().Id.Value;

            // NB: For any other endpoint, use agent's login, but for posting end-user Requests we must use the end user's email address so a separate client is required
            IZendeskClient userClient = new ZendeskClient(new Uri("https://yourcompany.zendesk.com/api/v2"), new ZendeskDefaultConfiguration(strEndUserEmail, "YOUR_TOKEN"));

            Request request = new Request()
            {
                Subject = strSubject,
                Priority = "Normal",
                Type = TicketType.problem,
                Comment = new TicketComment()
                {
                 Body = strDescription,
                 IsPublic = true,
                 Author = userID
                }
            };

            // Custom field- example
            request.CustomFields.Add(new CustomField() { Id = YourConstants.CUSTOM_ID_PRODUCT, Value = customProductCode });

            var postEndUserRequestResponse = userClient.Requests.Post(new RequestRequest() { Item = request });

            return postEndUserRequestResponse.Item;
        }

**Comment by kate-r** [comment]
Glad to hear it's all working for you now.
