### ISSUE TITLE
v3.1.0-alpha-372 Organizations.UpdateAsync() doesn't update properties/custom fields

### ISSUE THREAD

**Issue by matthewpetch** [justeat/ZendeskApiClient#120]
Might just be me doing something wrong, but trying to update an Organization just returns the unchanged organization 

Here's an example of what I'm trying 

            var myOrg = await client.Organizations.GetAsync(360000000001);  

            myOrg.CustomFields["address_line_2"] = "test";  

            myOrg.Details = "test test test";  

            var x = await client.Organizations.UpdateAsync(myOrg);

Works in version 3.0.0-beta-298

**Comment by LoadData** [comment]
Hi @matthewpetch!

Sorry for the delay in responding to this! I've tested this against the latest alpha of the client(3.3.2-alpha-493), and it appears to be working as expected.

Could you let us know if you continue having issues with this?

**Comment by jonathanstowell** [comment]
I guess we can close this one down if you tested and it works @LoadData ? It's been 3 months.

**Comment by mikerogers123** [comment]
Closing as it has now been 4 years since the issue was created and 3 years since last activity
