### ISSUE TITLE
Some fields of int remains in v2 branch

### ISSUE THREAD

**Issue by dany1468** [justeat/ZendeskApiClient#123]
Hi ✋ Thank you for a wonderful job.

I am currently using 2.0.4.
In my Zendesk app, Ticket's `ticket_form_id` is beyond the range of integers, and the process handling the ticket crashes.

I found the following PR. Are you planning to backport this content to v2?
https://github.com/justeat/ZendeskApiClient/pull/77

In the v2_hotfix branch, group_id changed to long type, so I thought that other attributes might be supported too.
https://github.com/justeat/ZendeskApiClient/pull/114

**Comment by mikerogers123** [comment]
Hi @dany1468, apologies for the delayed response. This was introduced in version 2.0.27, I believe. See https://github.com/justeat/ZendeskApiClient/pull/130/files for more detail 👍
