### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel. 

### ISSUE THREAD

**Issue by brakim** [justeat/ZendeskApiClient#133]
Hi, im using the current 2.0.26 version of the wrapper and now all of the sudden i get the message "The request was aborted: Could not create SSL/TLS secure channel. " whenever i try to use the client.

I did a mockup of the request with Postman and the API credentials work.

Any ideas?

**Comment by brakim** [comment]
Fixed in [PR](https://github.com/justeat/ZendeskApiClient/pull/134)

**Comment by ixedo** [comment]
In what release is this fix included?

**Comment by corneliuskopp** [comment]
This has been fixed in version [2.0.29](https://www.nuget.org/packages/ZendeskApi.Client/2.0.29).
