### ISSUE TITLE
Is there a way to search for Field1=x OR Field2=y using WithFilter or other?

### ISSUE THREAD

**Issue by axelgunn** [justeat/ZendeskApiClient#138]
I noticed that the .WithFilter() basically builds an array that is later used to BuildQuery().
Is there a way for example to OR two conditions?
example from sql: "where serial = 1234 OR device = 1"

**Comment by jonathanstowell** [comment]
Hi @axelgunn 

You should be able to use .WithQueryString to provide zendesks query language directly.
