### ISSUE TITLE
Possible problem with HttpClient

### ISSUE THREAD

**Issue by MaximTkachenko** [justeat/ZendeskApiClient#141]
Hello!
I see you create HttpClient for every request. Do you check occupied tcp ports during big number of requests? I mean problem described here https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by jonathanstowell** [comment]
Support for HttpClientFactory has been added: https://github.com/justeat/ZendeskApiClient/blob/master/src/ZendeskApi.Client/Extensions/ServiceCollectionExtensions.cs#L28

Closing.
