### ISSUE TITLE
Delete Ticket response

### ISSUE THREAD

**Issue by oshastitko** [justeat/ZendeskApiClient#145]
public async Task DeleteAsync(long ticketId)
        {
            using (_loggerScope(_logger, $"DeleteAsync({ticketId})"))
            using (var client = _apiClient.CreateClient(ResourceUri))
            {
                var response = await client.DeleteAsync(ticketId.ToString()).ConfigureAwait(false);

                if (response.StatusCode != HttpStatusCode.Ok)
                {
                    throw await new ZendeskRequestExceptionBuilder()
                                    .WithResponse(response)
                                    .WithExpectedHttpStatus(HttpStatusCode.OK)
                                    .WithHelpDocsLink("core/tickets#delete-ticket")
                                    .Build();
                }
            }
        }

It expected "Ok" http status code, but really it returns "204" (No Content). 
Should be:

                if (response.StatusCode != HttpStatusCode.NoContent)
                {
                    throw await new ZendeskRequestExceptionBuilder()
                                    .WithResponse(response)
                                    .WithExpectedHttpStatus(HttpStatusCode.OK)
                                    .WithHelpDocsLink("core/tickets#delete-ticket")
                                    .Build();
                }

**Comment by LoadData** [comment]
This was resolved in #152. Will now close.
