### ISSUE TITLE
Search sort by descending by default is not supported

### ISSUE THREAD

**Issue by cserkaran** [justeat/ZendeskApiClient#146]
As we can see in the zendesk rest api implementation, the listing of search results sort_order is desc by default. The client has a bug where it is not considered, and even on passing sort order as descending,
sort is still done by descending.
![image](https://user-images.githubusercontent.com/7068938/50327586-dbcb6b00-0543-11e9-91fb-25001399b320.png)

**Comment by cserkaran** [comment]
Have a fix ready. Raising a PR soon.

**Comment by hjaltethor** [comment]
Thanks for the PR! I've just merged it and will be releasing a new version of the client later today.
