### ISSUE TITLE
TicketUpdateRequest.cs  wrong type of ExternalId property.

### ISSUE THREAD

**Issue by vindemi** [justeat/ZendeskApiClient#169]
As the topic says, there is a discrepancy of ExternalId property in classes. ZendeskApi stands with **string** type of this property. In The class TicketUpdateRequest.cs there is a **long?** type.

```
[JsonProperty("external_id")]

public long? ExternalId { get; set; }
```

**Comment by LoadData** [comment]
Good catch. Resolved in latest PR #170.
