### ISSUE TITLE
Query string values are not URL encoded

### ISSUE THREAD

**Issue by omar** [justeat/ZendeskApiClient#21]
Reproduction steps:

1. Create a Zendesk user with a phone number of  `+1555555555`.
2. Create a query for searching for the user based on the phone number value:
```
var userQuery = new ZendeskQuery<User>()
    .WithCustomFilter("phone", "+1555555555");

var userResult = _zendeskClient.Search.Find(userQuery);
```
3. No results are returned.

Digging in the source code, the issue is that the value `+1555555555` is not URL encoded, so the `+` is rendered incorrectly. The URL generated by the URL builder is:

`https://my.zendesk.com/api/v2/search?query=type:user+phone:+1555555555&sort_by=created_at&sort_order=desc&page=1&per_page=15`

It should be 

`https://my.zendesk.com/api/v2/search?query=type:user+phone:%2B1555555555&sort_by=created_at&sort_order=desc&page=1&per_page=15`

Note the `+` was encoded to `%2B` in the query string value.

**Comment by omar** [comment]
@kate-r can you create a NuGet package for the changes so far? Looking to deploy this to production soon on our end.

**Comment by kate-r** [comment]
Hi,
I created one for the changes to the user identity put request already.

The user_fields change will go out tomorrow morning.

Kate

----- Reply message -----

**Comment by omar** [comment]
Anyway you can push these out today? I want to push our code to production but need a NuGet package to reference for our build server. Don't want to setup a temporary NuGet package.

Even if this is an alpha release to NuGet, I'd add it.

**Comment by kate-r** [comment]
Hi,

Take a look now. 1.0.73.0.

Kate

----- Reply message -----

**Comment by omar** [comment]
Thank you for getting this out and thank you for this library.
