### ISSUE TITLE
Satisfaction rating info

### ISSUE THREAD

**Issue by KevinJosephMorin** [justeat/ZendeskApiClient#26]
Kate,

Would it be fairly easy for you to expose ticket Satisfaction Rating information?  I am seeing it as satisfaction_rating on tickets.  I assume it is a temporary holding variable since it is all lower case.

Thanks.

**Comment by kate-r** [comment]
Hi,

I'm taking a look at this. Satisfaction Ratings a bit more complicated than just enabling a field: https://developer.zendesk.com/rest_api/docs/core/satisfaction_ratings#list-satisfaction-ratings. I need to add a new resource. Hopefully shouldn't take too long.

Kate

**Comment by kate-r** [comment]
Try the latest version of the client for this functionality.

Sorry, this took a while. Satisfaction ratings require configuration in your zendesk account which ours didn't previously had so I had to get that set up first.
