### ISSUE TITLE
ErrorResponse.Detail is never used when building ZendeskRequestException

### ISSUE THREAD

**Issue by automatorJames** [justeat/ZendeskApiClient#269]
Although the error response body from Zendesk is used to set the ErrorResponse.Details property, that property is never referenced. This  omits useful error reasons from being returned in the ZendeskRequestException message.

For example, after the user calls Client.Users.CreateAsync with a UserCreateRequest that has an email address that already exists in the user's Zendesk instance, the ZendeskRequestException error message returned to the user doesn't state the reason for failure (screenshot left). Compare this to the raw API response body returned via Postman (screenshot right), which says "Email: some@email.com is already being used by another user".

**Comparison of error message returned by ZendeskApiClient and raw error content body returned by Zendesk API**
![image](https://user-images.githubusercontent.com/67557669/224428313-c3142d01-b51d-4934-8e6c-c9e190a7d540.png)

This issue could be resolved by serializing the Detail property into the appended message.

**Comment by mikerogers123** [comment]
Hi @automatorJames, I've just merged this. Should be available in release [7.0.1](https://github.com/justeat/ZendeskApiClient/releases/tag/v7.0.1)
