### ISSUE TITLE
Migrate from AppVeyor to GitHub Actions

### ISSUE THREAD

**Issue by martincostello** [justeat/ZendeskApiClient#280]
This repo is the outlier amongst JET's .NET OSS projects now in that it is the only one using AppVeyor for CI  still.

To make permissions management easier to deal with centrally, this repository should migrate to use GitHub Actions to build and publish the NuGet package.

Here's an example of the workflow other packages use: [build.yml](https://github.com/justeat/httpclient-interception/blob/main/.github/workflows/build.yml)

**Comment by martincostello** [comment]
@Ud0o This is completed now, right? Can I archive off the AppVeyor setup?

**Comment by Ud0o** [comment]
@martincostello Hi, yes all done.
