### ISSUE TITLE
Unable to add tags to tickets

### ISSUE THREAD

**Issue by bmnielsen** [justeat/ZendeskApiClient#32]
The tags property on tickets doesn't appear to be hooked up to the Zendesk API. The values don't end up on the Zendesk ticket on post ticket, and it doesn't look like they are returned on get ticket either.

**Comment by kate-r** [comment]
Hi,

We don't use tags at JUST EAT and I only implemented the code we use here in the client before open sourcing it.

I'll take a look at adding in tags, unless you want to send a pull request for it?

Thanks,

Kate

**Comment by kate-r** [comment]
I've merged the PR for this and published the updated client.
