### ISSUE TITLE
Adding Ticket->Via->Source->From to API

### ISSUE THREAD

**Issue by KevinJosephMorin** [justeat/ZendeskApiClient#41]
Kate,

Would it be possible to add to the TicketCommentList the following: Via->Source->From

Here is a quick video showing exactly what I am after: https://crmtools.macroconnect.net/screencastviewer.ashx?screencastid=coXv3Kh081

Thanks,

Kevin

**Comment by kate-r** [comment]
Hi,

I had a look at this using our JUST EAT zendesk sandbox and I can't get the to/from fields to populate, even when making the call directly from fiddler. I've had similar issues with other objects before due to settings in our just eat zendesk account.

I can see from your video that you've got the via fields working so I have created a prerelease version of the zendesk api client here https://www.nuget.org/packages/ZendeskApi.Client/1.0.110-pre with the via fields available. Give that a try and let me know how you get on. 

Kate

**Comment by KevinJosephMorin** [comment]
You rule!



That worked perfectly.  Are you going to push it out officially or will that happen later?



Here is a sample of how I used it:



            Dim objTicketComments = objAPI.TicketComments.GetAll(pintZDTicketId)

            Dim intAuditCount As Integer = objTicketComments.TotalCount
            For i = 0 To intAuditCount - 1 'LOOKUP ZENDESK COMMENTS
                Dim strMacroEmployeeThatCreatedTicketViaEmail As String
                If objTicketComments.Results(i).Via.Channel = "email" AndAlso objTicketComments.Results(i).Via.Source.From IsNot Nothing Then
                    For Each objContact In objTicketComments.Results(i).Via.Source.From("original_recipients")
                        If UCase(objContact.ToString).Contains("@MACROCONNECT.ZENDESK.COM") = False Then strMacroEmployeeThatCreatedTicketViaEmail = objContact.ToString
                    Next
                End If
            Next


Kevin J. Morin
Chief Technology Officer

Macro Connect, Inc
(888) 578-7976 ext. 803
Web<http://www.macroconnect.net/> | Facebook<https://www.facebook.com/MacroConnect?fref=ts> | LinkedIn<http://www.linkedin.com/company/1978319?trk=tyah>

How am I doing?  Click this link<http://www.surveymonkey.com/s/8DT7XBM> to provide feedback.

Macro Connect customers: Please do not email staff members directly to submit tasks, especially if you have an urgent issue.  We are frequently in the field and unable to quickly respond to email.  Follow your organization’s procedure for requesting service or submit a support ticket here<https://macroconnect.zendesk.com/>.
________________________________

**Comment by KevinJosephMorin** [comment]
Kate,



Since upgrading to the latest DLL, my code for deleting Zendesk tickets has started to fail.



Here is the code:

        Dim objZDConfig As New ZendeskDefaultConfiguration(pubstrZDUser, pubstrZDToken)
        Dim objAPI As IZendeskClient = New ZendeskClient(New Uri(pubstrZDURL), objZDConfig)
        objAPI.Tickets.Delete(pintZenDeskID)





Here is the stack trace:

   at ZendeskApi.Client.ClientBase.ValidateResponse(IHttpResponse response)
   at ZendeskApi.Client.ClientBase.Delete(Uri requestUri)
   at ZendeskApi.Client.Resources.ZendeskResource`1.Delete(Int64 id, Nullable`1 parentId)
   at ZendeskApi.Client.Resources.ZendeskResource`1.Delete(Int64 id)
   at ZenDeskReceiver.DeleteZD(Int32 pintZenDeskID) in C:\Users\kevin_000\Documents\Visual Studio 2010\WebSites\CRM\CRMTools\consulting\ZenDeskReceiver.ashx:line 184
   at ZenDeskReceiver.Maintenance() in C:\Users\kevin_000\Documents\Visual Studio 2010\WebSites\CRM\CRMTools\consulting\ZenDeskReceiver.ashx:line 142





Any idea what it might be?


Kevin J. Morin
Chief Technology Officer

Macro Connect, Inc
(888) 578-7976 ext. 803
Web<http://www.macroconnect.net/> | Facebook<https://www.facebook.com/MacroConnect?fref=ts> | LinkedIn<http://www.linkedin.com/company/1978319?trk=tyah>

How am I doing?  Click this link<http://www.surveymonkey.com/s/8DT7XBM> to provide feedback.

Macro Connect customers: Please do not email staff members directly to submit tasks, especially if you have an urgent issue.  We are frequently in the field and unable to quickly respond to email.  Follow your organization’s procedure for requesting service or submit a support ticket here<https://macroconnect.zendesk.com/>.
________________________________
From: Kevin J. Morin [kevin.morin@macroconnect.net]
Sent: Thursday, December 03, 2015 11:19 AM
To: justeat/ZendeskApiClient; justeat/ZendeskApiClient
Cc: KevinJosephMorin
Subject: RE: [ZendeskApiClient] Adding Ticket->Via->Source->From to API (#41)


You rule!



That worked perfectly.  Are you going to push it out officially or will that happen later?



Here is a sample of how I used it:



            Dim objTicketComments = objAPI.TicketComments.GetAll(pintZDTicketId)

            Dim intAuditCount As Integer = objTicketComments.TotalCount
            For i = 0 To intAuditCount - 1 'LOOKUP ZENDESK COMMENTS
                Dim strMacroEmployeeThatCreatedTicketViaEmail As String
                If objTicketComments.Results(i).Via.Channel = "email" AndAlso objTicketComments.Results(i).Via.Source.From IsNot Nothing Then
                    For Each objContact In objTicketComments.Results(i).Via.Source.From("original_recipients")
                        If UCase(objContact.ToString).Contains("@MACROCONNECT.ZENDESK.COM") = False Then strMacroEmployeeThatCreatedTicketViaEmail = objContact.ToString
                    Next
                End If
            Next


Kevin J. Morin
Chief Technology Officer

Macro Connect, Inc
(888) 578-7976 ext. 803
Web<http://www.macroconnect.net/> | Facebook<https://www.facebook.com/MacroConnect?fref=ts> | LinkedIn<http://www.linkedin.com/company/1978319?trk=tyah>

How am I doing?  Click this link<http://www.surveymonkey.com/s/8DT7XBM> to provide feedback.

Macro Connect customers: Please do not email staff members directly to submit tasks, especially if you have an urgent issue.  We are frequently in the field and unable to quickly respond to email.  Follow your organization’s procedure for requesting service or submit a support ticket here<https://macroconnect.zendesk.com/>.
________________________________

**Comment by KevinJosephMorin** [comment]
Sorry to blast you twice.  It might be a change on the Zendesk side too.  We don't fire off the delete code very often.  Perhaps not in a really long time.


Kevin J. Morin
Chief Technology Officer

Macro Connect, Inc
(888) 578-7976 ext. 803
Web<http://www.macroconnect.net/> | Facebook<https://www.facebook.com/MacroConnect?fref=ts> | LinkedIn<http://www.linkedin.com/company/1978319?trk=tyah>

How am I doing?  Click this link<http://www.surveymonkey.com/s/8DT7XBM> to provide feedback.

Macro Connect customers: Please do not email staff members directly to submit tasks, especially if you have an urgent issue.  We are frequently in the field and unable to quickly respond to email.  Follow your organization’s procedure for requesting service or submit a support ticket here<https://macroconnect.zendesk.com/>.
________________________________
From: Kevin J. Morin [kevin.morin@macroconnect.net]
Sent: Sunday, December 06, 2015 11:57 AM
To: justeat/ZendeskApiClient; justeat/ZendeskApiClient
Cc: KevinJosephMorin
Subject: RE: [ZendeskApiClient] Adding Ticket->Via->Source->From to API (#41)


Kate,



Since upgrading to the latest DLL, my code for deleting Zendesk tickets has started to fail.



Here is the code:

        Dim objZDConfig As New ZendeskDefaultConfiguration(pubstrZDUser, pubstrZDToken)
        Dim objAPI As IZendeskClient = New ZendeskClient(New Uri(pubstrZDURL), objZDConfig)
        objAPI.Tickets.Delete(pintZenDeskID)





Here is the stack trace:

   at ZendeskApi.Client.ClientBase.ValidateResponse(IHttpResponse response)
   at ZendeskApi.Client.ClientBase.Delete(Uri requestUri)
   at ZendeskApi.Client.Resources.ZendeskResource`1.Delete(Int64 id, Nullable`1 parentId)
   at ZendeskApi.Client.Resources.ZendeskResource`1.Delete(Int64 id)
   at ZenDeskReceiver.DeleteZD(Int32 pintZenDeskID) in C:\Users\kevin_000\Documents\Visual Studio 2010\WebSites\CRM\CRMTools\consulting\ZenDeskReceiver.ashx:line 184
   at ZenDeskReceiver.Maintenance() in C:\Users\kevin_000\Documents\Visual Studio 2010\WebSites\CRM\CRMTools\consulting\ZenDeskReceiver.ashx:line 142





Any idea what it might be?


Kevin J. Morin
Chief Technology Officer

Macro Connect, Inc
(888) 578-7976 ext. 803
Web<http://www.macroconnect.net/> | Facebook<https://www.facebook.com/MacroConnect?fref=ts> | LinkedIn<http://www.linkedin.com/company/1978319?trk=tyah>

How am I doing?  Click this link<http://www.surveymonkey.com/s/8DT7XBM> to provide feedback.

Macro Connect customers: Please do not email staff members directly to submit tasks, especially if you have an urgent issue.  We are frequently in the field and unable to quickly respond to email.  Follow your organization’s procedure for requesting service or submit a support ticket here<https://macroconnect.zendesk.com/>.
________________________________
From: Kevin J. Morin [kevin.morin@macroconnect.net]
Sent: Thursday, December 03, 2015 11:19 AM
To: justeat/ZendeskApiClient; justeat/ZendeskApiClient
Cc: KevinJosephMorin
Subject: RE: [ZendeskApiClient] Adding Ticket->Via->Source->From to API (#41)


You rule!



That worked perfectly.  Are you going to push it out officially or will that happen later?



Here is a sample of how I used it:



            Dim objTicketComments = objAPI.TicketComments.GetAll(pintZDTicketId)

            Dim intAuditCount As Integer = objTicketComments.TotalCount
            For i = 0 To intAuditCount - 1 'LOOKUP ZENDESK COMMENTS
                Dim strMacroEmployeeThatCreatedTicketViaEmail As String
                If objTicketComments.Results(i).Via.Channel = "email" AndAlso objTicketComments.Results(i).Via.Source.From IsNot Nothing Then
                    For Each objContact In objTicketComments.Results(i).Via.Source.From("original_recipients")
                        If UCase(objContact.ToString).Contains("@MACROCONNECT.ZENDESK.COM") = False Then strMacroEmployeeThatCreatedTicketViaEmail = objContact.ToString
                    Next
                End If
            Next


Kevin J. Morin
Chief Technology Officer

Macro Connect, Inc
(888) 578-7976 ext. 803
Web<http://www.macroconnect.net/> | Facebook<https://www.facebook.com/MacroConnect?fref=ts> | LinkedIn<http://www.linkedin.com/company/1978319?trk=tyah>

How am I doing?  Click this link<http://www.surveymonkey.com/s/8DT7XBM> to provide feedback.

Macro Connect customers: Please do not email staff members directly to submit tasks, especially if you have an urgent issue.  We are frequently in the field and unable to quickly respond to email.  Follow your organization’s procedure for requesting service or submit a support ticket here<https://macroconnect.zendesk.com/>.
________________________________

**Comment by kate-r** [comment]
Hi,

Did you get this sorted?

Kate

**Comment by KevinJosephMorin** [comment]
Kate,



I still need help with two things:



1) Figuring out why the API delete function errors

2) Moving the Source changes from Pre to production



Much appreciated as always!


Kevin J. Morin
Chief Technology Officer

Macro Connect, Inc
(888) 578-7976 ext. 803
Web<http://www.macroconnect.net/> | Facebook<https://www.facebook.com/MacroConnect?fref=ts> | LinkedIn<http://www.linkedin.com/company/1978319?trk=tyah>

How am I doing?  Click this link<http://www.surveymonkey.com/s/8DT7XBM> to provide feedback.

Macro Connect customers: Please do not email staff members directly to submit tasks, especially if you have an urgent issue.  We are frequently in the field and unable to quickly respond to email.  Follow your organization’s procedure for requesting service or submit a support ticket here<https://macroconnect.zendesk.com/>.
________________________________

**Comment by kate-r** [comment]
Hi,

The problem with the delete method is that Zendesk have changed their response code for a successful delete request to be '204 - No Content'. The request to delete the item works, however, this client does not currently see a 'No Content' response as a successful response code. 

I will update this now and push a new version.

Kate

**Comment by kate-r** [comment]
Done

**Comment by KevinJosephMorin** [comment]
I am good to go.  I really appreciate you.


Kevin J. Morin
Chief Technology Officer

Macro Connect, Inc
(888) 578-7976 ext. 803
Web<http://www.macroconnect.net/> | Facebook<https://www.facebook.com/MacroConnect?fref=ts> | LinkedIn<http://www.linkedin.com/company/1978319?trk=tyah>

How am I doing?  Click this link<http://www.surveymonkey.com/s/8DT7XBM> to provide feedback.

Macro Connect customers: Please do not email staff members directly to submit tasks, especially if you have an urgent issue.  We are frequently in the field and unable to quickly respond to email.  Follow your organization’s procedure for requesting service or submit a support ticket here<https://macroconnect.zendesk.com/>.
________________________________
