### ISSUE TITLE
Installation instructions and badges for NuGet

### ISSUE THREAD

**Issue by 3686** [justeat/ZendeskApiClient#64]
Hey, it's not that obvious how to install and use this ;)

**Comment by corneliuskopp** [comment]
Hello 3686, 

to install run `Install-Package ZendeskApi.Client` in your nuget package manager console (this package is [published on nuget.org](http://www.nuget.org/packages/ZendeskApi.Client/)). The README.md contains some pointers on how to instantiate clients and access resources; you will need to grab the appropriate URL for your zendesk instance and configure a token as per their documentation.

Are there specific problems we can help you with?
