### ISSUE TITLE
Odd namespace for ZendeskResource

### ISSUE THREAD

**Issue by RoosterDragon** [justeat/ZendeskApiClient#65]
This full name of `ZendeskResource<T>` is [`ZendeskApi.Client.Resources.ZendeskApi.Client.Resources.ZendeskResource<T>`](https://github.com/justeat/ZendeskApiClient/blob/cf7896e0d9366ba12d136cddf8a5c5c3ba76b501/src/ZendeskApi.Client/Resources/ZendeskResource.cs#L15).
I assume that is not intended. :)

**Comment by kbrimble** [comment]
`ZendeskResource` has been removed so this is no longer relevant 😄
