### ISSUE TITLE
Dotnet Standard

### ISSUE THREAD

**Issue by Jetski5822** [justeat/ZendeskApiClient#69]
Hi Justeat Team,

I need this to be dotnet standard compliant. Have you done any work on this yet, or would you be open to a PR for this?

N

**Comment by JosephWoodward** [comment]
Looks like it'd be pretty straight forward, with the main issue being SpecFlow (https://icanhasdot.net/result?github=justeat~2FZendeskApiClient), though that's just the tests so you'd be able to target .NET Standard for the build binary.

**Comment by Jetski5822** [comment]
PR in, however I have refactored alot. I felt like there was alot of indirection in the API, so have tried to clean that up to remove noise.

The PR is just for technical feedback at this stage.

**Comment by Jetski5822** [comment]
PR Done - ready for proper feedback now. Not sure this is a true estimate of the changes :)

![image](https://user-images.githubusercontent.com/619530/27039779-e53f9072-4f86-11e7-818b-50ef78a21598.png)
