### ISSUE TITLE
ZendeskApiClient TicketFields giving error

### ISSUE THREAD

**Issue by krnrajput** [justeat/ZendeskApiClient#71]
An exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in ZendeskApi.Client.dll but was not handled in user code
Additional information: Error deserializing type 'ZendeskApi.Contracts.Responses.TicketFieldListResponse', see inner exception for more details

Code
IListResponse<TicketField> TicketFieldDetail = null;
TicketFieldDetail = client.TicketFields.GetAll();
erlier it was working fine

I'm using "Zendesk Api Client 2.0.17" nuget package
https://www.nuget.org/packages/ZendeskApi.Client/2.0.24
also tried with updated version

**Comment by Jetski5822** [comment]
@krnrajput Try the new API, its much neater and should provide you better error messages if any appear,

**Comment by OliIntraz** [comment]
I do also get an exception when calling the client.TicketFields.GetAllAsync() method, using version 3.1.0-alpha-315. The error is a JsonReaderException, "JSON integer 114094431312 is too large or small for an Int32".
I am using .NET Core 2.0.

**Comment by Jetski5822** [comment]
All integers should be longs, can you see one that isn't?

**Comment by OliIntraz** [comment]
Hi, one of the fastest reply I’ve ever good, good work😊

 

The TicketField.Id property is indeed a long (or a long?) so that isn’t a problem. I am not doing any serializing stuff, this error occurs when I am calling the client.TicketFields.GetAllAsync() method

 

                var ticketFields = await client.TicketFields.GetAllAsync();

 

The exact exception message is:

Message = "JSON integer 114094431312 is too large or small for an Int32. Path 'ticket_fields[12].custom_field_options[0].id', line 1, position 7996."

 

The CustomFieldOption.Id property is an int and is probably the culprit.

 

Best regards,

   Oli

**Comment by Jetski5822** [comment]
Ah!!! Yup!! That's probably the culprit... it's funny as there site says ints, but in C# land it's a long. 

I'll go through and do a PR for this stuff over the weekend. I'm sure the JE boys will have no problem merging in. N

**Comment by OliIntraz** [comment]
Great, thanks for that😊

 

Best regards,

   Oli

**Comment by OliIntraz** [comment]
Hi again, I just updated to alpha 339 and still get this error. The code was not fixed (the CustomFieldOptions.Id property is still an int but should be long), any change of getting this fixed?

**Comment by hjaltethor** [comment]
I've created #106 to fix this issue and had a look through the rest of the code to see if I could find any ints that shouldn't be there (I couldn't).

I'll get it merged by one of the other maintainers soon and hopefully it'll solve your issue.

**Comment by hjaltethor** [comment]
Please give version 344 a go

**Comment by OliIntraz** [comment]
Yes, this works correctly now, many thanks:)

**Comment by hjaltethor** [comment]
Excellent, glad to hear. I'll close this ticket.
