### ISSUE TITLE
Adding new comments to tickets 

### ISSUE THREAD

**Issue by yonahs** [justeat/ZendeskApiClient#72]
@kate-r 
I apoligize for creating new issue, but the previous one (https://github.com/justeat/ZendeskApiClient/issues/9)  was closed and I am not sure on the correct protocol for this.

Anyways, here is my issue

I have tried using the following codes (tried both) to add a comment to an existing ticket but it does not work and all it does is create a new ticket.

       ```
 Dim ticketID = 257
        Dim rqst As New TicketRequest
        Dim rsp = client.Tickets.Get(ticketID)
        Dim ticket = rsp.Item
        Dim comment As New TicketComment
        ticket.Comment = comment
        comment.Body = "Testing API"
        comment.IsPublic = True
        comment.Author = 22420874907
        comment.Type = TicketEventType.Comment
        rqst.Item = ticket
        client.Tickets.Post(rqst)
```
and

```
        Dim ticketID = 257
        Dim rqst As New TicketRequest
        Dim newTicket As New Ticket
        rqst.Item = newTicket
        newTicket.Id = ticketID
        Dim comment As New TicketComment
        newTicket.Comment = comment
        comment.Body = "Testing API"
        comment.IsPublic = True
        comment.Author = 22420874907
        comment.Type = TicketEventType.Comment
        client.Tickets.Post(rqst)

```
I appreciate any help you can give in guiding me to my mistake

Thanks

**Comment by Jetski5822** [comment]
So I think I see the issue here.... you are doing client.Tickets.Post(rqst), where as you want to do client.Tickets.Put(rqst)

However, if you use the new API, you can do this...

ITicketCommentsResource resource = _client.TicketComments.
resource.AddComment(<ticektId>, <ticketComment>)

Enjoy.

**Comment by corneliuskopp** [comment]
Since it's been a while since the last comment, I hope this solved your issue! If not, feel free to come back here and add more details.
