### ISSUE TITLE
Getting Issue while getting response from client.Tickets.Post method

### ISSUE THREAD

**Issue by virendrayadav100** [justeat/ZendeskApiClient#73]
Hi,

I am getting below error while getting response from client.Tickets.Post method.

Newtonsoft.Json.JsonSerializationException: JSON integer 114094276114 is too large or small for an Int32. Path 'ticket.group_id'

Ticket is posted successfully to zendesk. 

Please help

**Comment by virendrayadav100** [comment]
I have checked Group Id for my default group is 114094276114 , that's why it is not working.

Please change type from int? to long? for Group Id Field

**Comment by Stormsys** [comment]
@virendrayadav100 We would be happy to take a PR for this. I have also suggested it to be included in the #70 update too.

**Comment by corneliuskopp** [comment]
This has been fixed in [2.0.25](https://www.nuget.org/packages/ZendeskApi.Client/2.0.25). If there are any issues with this / a later version, feel free to reopen this issue!
