### ISSUE TITLE
Unable to upload attachment using client.uploads.post

### ISSUE THREAD

**Issue by virendrayadav100** [justeat/ZendeskApiClient#83]
Hi,

i am new with ZendeskApiClient, i don't know how to upload attachments.
Please suggest any example.

Thanks,

**Comment by Jetski5822** [comment]
Have you looked at the tests? https://github.com/justeat/ZendeskApiClient/blob/master/test/ZendeskApi.Client.Tests/Resources/AttachmentsResourceTests.cs

**Comment by corneliuskopp** [comment]
I assume the docs have solved your issue! If you find any problems with the library, feel free to reopen this issue.
