### ISSUE TITLE
The object returned by Tickets.CreateAsync method is not valid

### ISSUE THREAD

**Issue by OliIntraz** [justeat/ZendeskApiClient#85]
I have been trying version 3.1.0-alpha-315 and noticed that the Tickets.CreateAsync method doesn't populate the returned TicketResponse object correctly, all the values are null/0.
   var ticketResponse = await client.Tickets.CreateAsync(ticketRequest);

It would be very beneficially to get the newly created object back with the newly created id and other properties.
I am using .NET Core 2.0.

**Comment by Jetski5822** [comment]
Do you know if it worked on previous versions?

**Comment by OliIntraz** [comment]
No, I haven’t tried it.

 

The CreateAsync method in the TicketResource.cs class uses .ConfigureAwait(false), could that be the source of the problem? As I understand you should not use ConfigureAwait(false) when you have code after the await that needs the context, i.e. the context after the Ticket has been created.

 

Best regards,

   Oli

**Comment by OliIntraz** [comment]
A similar error occurs when fetching ticket by id, the returned object is not populated correctly (all properties are null/0). If the ticket is not found then a null object is returned which is correct.
   var ticket = await client.Tickets.GetAsync(id);
The client.Tickets.ListAsync() method works correctly though, all the returned tickets are populated correctly.

**Comment by harsheet** [comment]
Its working fine in previous version.

**Comment by corneliuskopp** [comment]
Hello! Could you confirm if this is still an issue in newer versions? I tried it with a recent version of the library and it seemed to work fine now. Let us know if you run into further problems!

**Comment by jonathanstowell** [comment]
@corneliuskopp Do you think we should close this one off? It's been working for us in the newer versions and 3 months since we asked for an update :-)

Having a bit of a tidy up of issues!

**Comment by corneliuskopp** [comment]
Sounds like a plan!
Any onlookers, please do feel free to leave comments if this turns out to still be an issue. Thank you!
