### ISSUE TITLE
update userIdentity not working

### ISSUE THREAD

**Issue by EmmanuelAtx** [justeat/ZendeskApiClient#86]
we created a method that works. 2 bugs:
1. in the url for PUT, the id of the userIdentity needs to be added ("api/v2/users/{0}/identities/{1}")
2. The serialized json object needed to be inside {"identity":{Id:454 .... }}

`  
public async Task<UserIdentity> UpdateAsyncFix(UserIdentity identity)
        {
            string ResourceUriFormat = "api/v2/users/{0}/identities/{1}";
            using (var client = _apiClient.CreateClient())
            {
                var idWrapper =  new identity {Identity = identity};
                var response = await client.PutAsJsonAsync(string.Format(ResourceUriFormat, identity.UserId, identity.Id), idWrapper).ConfigureAwait(false);

                if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
                {
                    return null;
                }

                response.EnsureSuccessStatusCode();

                return await response.Content.ReadAsAsync<UserIdentity>();
            }
        }
    }
    [JsonObject("identity")]
    internal class identity
    {
        public UserIdentity Identity { get; set; }
    }`

**Comment by jonathanstowell** [comment]
I think this has been fixed in the latest V3-alpha version.

Thanks.
