### ISSUE TITLE
Adding new comments to tickets

### ISSUE THREAD

**Issue by KevinJosephMorin** [justeat/ZendeskApiClient#9]
I have been testing your code and found it to work great.  However, I am not sure how to add comments to a ticket.

Is there a way to do it?

If so, can you send me a code sample on adding comments to tickets with your solution?

**Comment by kate-r** [comment]
Glad you've found it helpful.

I've added an extra test to demonstrate adding a comment to a ticket and getting all comments for a ticket. You can see the test here https://github.com/justeat/ZendeskApiClient/blob/master/src/ZendeskApi.Acceptance/TicketComments.feature

Hope that helps.

**Comment by KevinJosephMorin** [comment]
Kate,



I am new to GitHub.  Can you explain "extra test" further?  Are you saying that the .Net API doesn't currently support Put and Post but that it can in the future?


Kevin J. Morin
Chief Technology Officer

Macro Connect, Inc
(888) 578-7976 ext. 803
Web<http://www.macroconnect.net/> | Facebook<https://www.facebook.com/MacroConnect?fref=ts> | LinkedIn<http://www.linkedin.com/company/1978319?trk=tyah>

How am I doing?  Click this link<http://www.surveymonkey.com/s/8DT7XBM> to provide feedback.

Macro Connect customers: Please do not email staff members directly to submit tasks, especially if you have an urgent issue.  We are frequently in the field and unable to quickly respond to email.  Follow your organization’s procedure for requesting service or submit a support ticket here<https://crmtools.macroconnect.net/consulting/createticket.aspx>.
________________________________

**Comment by kate-r** [comment]
In the zendesk api, a ticket has a single comment object as a property. If you update this with a new comment it will be saved alongside the other comments that already exist for that ticket.

You need to create a client:

    private IZendeskClient _client;
    ...
    _client = new ZendeskClient(new Uri(ConfigurationManager.AppSettings["zendeskhost"]),
                new ZendeskDefaultConfiguration(ConfigurationManager.AppSettings["zendeskusername"], ConfigurationManager.AppSettings["zendesktoken"]));

That works like this using the .net client I've created:

    _client.Tickets.Post(new TicketRequest
                {
                    Item = new Ticket { Subject = subject, Comment = new TicketComment{ Body = "Some comment"}, Type = TicketType.task }
                });

To get all of the comments for a ticket, you can use the TicketComment resource in my .net client like this:

    _client.TicketComments.GetAll(myTicketId);

There is also further documentation on the ZendeskApi developer website: https://developer.zendesk.com/rest_api/docs/core/ticket_comments

**Comment by KevinJosephMorin** [comment]
Kate,



I had to take a couple weeks off in rewriting my ZenDesk code.



I am to the point where I am debugging and it looks like custom_fields don't work.



Have you run in to that?



Here are is some code snippets:

Dim objZDConfig As New ZendeskDefaultConfiguration(pubstrZDUser, pubstrZDToken)

Dim objAPI As IZendeskClient = New ZendeskClient(New Uri(pubstrZDURL), objZDConfig)

Dim objTicketLookup As IResponse(Of Ticket) = objAPI.Tickets.Get(pubintZDTicketId)

Dim strScheduledEnd As String = objTicketLookup.Item.custom_fields(0).Value



When I put a watcher on objTicketLookup.Item the custom_fields shows as Nothing.



With the older .Net API, I am able to pull custom_fields on the same ticket.


Kevin J. Morin
Chief Technology Officer

Macro Connect, Inc
(888) 578-7976 ext. 803
Web<http://www.macroconnect.net/> | Facebook<https://www.facebook.com/MacroConnect?fref=ts> | LinkedIn<http://www.linkedin.com/company/1978319?trk=tyah>

How am I doing?  Click this link<http://www.surveymonkey.com/s/8DT7XBM> to provide feedback.

Macro Connect customers: Please do not email staff members directly to submit tasks, especially if you have an urgent issue.  We are frequently in the field and unable to quickly respond to email.  Follow your organization’s procedure for requesting service or submit a support ticket here<https://crmtools.macroconnect.net/consulting/createticket.aspx>.
________________________________

**Comment by kate-r** [comment]
Hello,

This ZendeskApiClient was written by me, for one of our new internal systems at JUST EAT, which uses Zendesk. We try to be pretty Agile with how we work, so I only implemented the functionality that we actually needed, which at the time didn't include custom fields. If you look into the code, custom fields is a property, but it's Json ignored so that's why it doesn't come back.

I've had a look at the client and it doesn't seem like much work to add custom fields for tickets into the ticket response. I'll get that added in as soon as I can and redeploy the nuget package so you can work with custom fields.

I hope that helps.

Kate

**Comment by kate-r** [comment]
Take a look at the latest Nuget package. Hopefully that should fix your issue.

**Comment by KevinJosephMorin** [comment]
You are incredible.  Thanks for the super quick turn around.  Can I pay your for your time?



I found one more issue (that is probably the same type of problem).



I am not able to pull Attachments from tickets.  Here is the code that I am running:



.attachments is showing as Nothing



Dim objTicketComments = objAPI.TicketComments.GetAll(pintZDTicketId)

Dim intAuditCount As Integer = objTicketComments.TotalCount

For i = 0 To intAuditCount - 1

  Dim strAttachmentURLList As String = ""

  If objTicketComments.Results(i).attachments IsNot Nothing Then

    For Each Attachment In objTicketComments.Results(i).attachments

      strAttachmentURLList += "URL of Attachment: " & Attachment.ContentUrl & vbCrLf & vbCrLf

    Next

  End If

  msgbox(objTicketComments.Results(i).Body.ToString & strAttachmentURLList) 'MAY WANT TO USE HTML BODY INSTEAD

Next


Kevin J. Morin
Chief Technology Officer

Macro Connect, Inc
(888) 578-7976 ext. 803
Web<http://www.macroconnect.net/> | Facebook<https://www.facebook.com/MacroConnect?fref=ts> | LinkedIn<http://www.linkedin.com/company/1978319?trk=tyah>

How am I doing?  Click this link<http://www.surveymonkey.com/s/8DT7XBM> to provide feedback.

Macro Connect customers: Please do not email staff members directly to submit tasks, especially if you have an urgent issue.  We are frequently in the field and unable to quickly respond to email.  Follow your organization’s procedure for requesting service or submit a support ticket here<https://crmtools.macroconnect.net/consulting/createticket.aspx>.
________________________________

**Comment by KevinJosephMorin** [comment]
Do you think adding in attachment code to the API would be reasonably possible?  Can I pay you for your time?

**Comment by kate-r** [comment]
Hello,

I've updated the package with support for attachments. You can find the latest version here: https://www.nuget.org/packages/ZendeskApi.Client/

This project is Open Sourced under Apache V2 so no need to pay for anything. We'd already started on attachments so it wasn't much effort to finish off.

Kate

**Comment by KevinJosephMorin** [comment]
I am amazed again.  Thanks!

I just updated and am running .46 now.

The attachments don't seem to come across.  Below is the code I am running

When I debug, I am not getting in to the IF statement.  The "objTicketComments.Results(i).attachments" is showing as NOTHING

If objTicketComments.Results(i).attachments IsNot Nothing Then '*****THIS IS NOT WORKING PROPERLY WITH KATE'S API
                    For Each Attachment In objTicketComments.Results(i).attachments
                        strAttachmentURLList += "URL of Attachment: " & Attachment.ContentUrl & vbCrLf & vbCrLf '***THIS COULD PROBABLY RUN A READHTTP FROM STANDARDROUTINES TO GET THE ACTUAL FILE
                    Next
                    If strAttachmentURLList <> "" Then
                        strAttachmentURLList = vbCrLf & vbCrLf & strAttachmentURLList
                        strAttachmentURLList = strAttachmentURLList.TrimEnd() 'REMOVE TRAILING VBCRLF'S
                    End If
                End If

**Comment by kate-r** [comment]
Hi,

Try again, and make sure you get https://www.nuget.org/packages/ZendeskApi.Client/0.0.61.

Attachments is with a capital A. "objTicketComments.Results(i).Attachments".

As a heads up as well, to upload a file to the zendesk api:

    HttpPostedFileBase file = GetUploadedFile();
    
    IResponse<Upload> response = _client.Upload.Post(new UploadRequest
    {
         Item = file
    });

From that you get a token:

     string uploadToken = response.Item.Token;

Then you pass the token into your ticket comment:

    Ticket ticket = GetExistingTicket(ticketId);

    ticket.Comment = new TicketComment { Body = comment };
    
    ticket.Comment.AddAttachmentToComment(uploadToken);

     _client.Tickets.Put(new TicketRequest { Item = ticket });

Hope that helps.

Kate

**Comment by KevinJosephMorin** [comment]
Worked for me this time.  Thanks!

**Comment by kate-r** [comment]
Brilliant. I will close this issue.

**Comment by yonahs** [comment]
@kate-r :
Thanks for this API, but I can not get it to add a comment to an existing ticket.

```
Dim ticketID = 257
Dim rqst As New TicketRequest
Dim newTicket As New Ticket
rqst.Item = newTicket
newTicket.Id = ticketID
Dim comment As New TicketComment
newTicket.Comment = comment
comment.Body = "Testing API"
comment.IsPublic = True
comment.Author = 22420874907
comment.Type = TicketEventType.Comment
client.Tickets.Post(rqst)`
```
When I try this, Zendesk creates a new ticket.

What am I doing wrong?

Thanks again for your help
