### ISSUE TITLE
Create and update user

### ISSUE THREAD

**Issue by harsheet** [justeat/ZendeskApiClient#90]
If the user already exists, it should update the user and the statusCode should be 200 according to the documentation. But the api client code only handles 201, so it always throw an exception.

How to handle this?

Thanks

**Comment by LoadData** [comment]
Hi there!

Sorry for the delay in replying to this! Do you know what version of the client this was a problem in? It appears that this functionality was implemented in #111.

**Comment by jonathanstowell** [comment]
We should probably close this as its around 2 years old :-)

Functionality seems to have been implemented to resolve the original question.
