### ISSUE TITLE
Sharing Agreements

### ISSUE THREAD

**Issue by KevinJosephMorin** [justeat/ZendeskApiClient#99]
Kate,

I am trying to grab ticket sharing agreement info via the API.

I am using an older API 1.0.115.  I also tried with 1.0.142 and had the same limitation.  I tried to upgrade to 2.x.x and got errors.  If this is handled in 2.x.x, I can figure out what the errors are get 2.x.x. installed

Attached are two images of what I am seeing.

With fiddler I am seeing the sharing_agreement_ids populated but that data isn't showing up in Visual Studio.

If we can get the sharing_agreement_ids to show in Visual Studio, I then am interested in querying the sharing_agreements interface (here is an example https://macroconnect.zendesk.com/api/v2/sharing_agreements/20146366.json)

From there, I would want to grab remote_subdomain or name from {"sharing_agreement":{"id":20146366,"name":"MarkSetBot @ Zendesk","type":"inbound","status":"accepted","partner_name":null,"remote_subdomain":"marksetbot","created_at":"2017-10-15T14:03:36Z"}}

Is there any chance of that being built out?

Kevin

![ticket sharing2](https://user-images.githubusercontent.com/9454704/31586560-9abe4fb2-b1a0-11e7-9f0c-01447e6fb027.png)
![ticket sharing](https://user-images.githubusercontent.com/9454704/31586561-9ad87acc-b1a0-11e7-8450-c831d9312679.png)

**Comment by hjaltethor** [comment]
Hi Kevin

I'm sorry for the late response. I had a look at your issue, and it should be fixed in the latest version. It's currently tagged as an alpha, as it's seen a lot of changes, but it should be stable enough for you to use.

sharing_agreement_ids used to be ignored, which meant it wasn't mapped, but that changed in version 3 onwards.

**Comment by KevinJosephMorin** [comment]
Hjalte,

Thanks for the update.  Can you check out my other ticket and see if it is an easy fix?  https://github.com/justeat/ZendeskApiClient/issues/140

Kevin

**Comment by jonathanstowell** [comment]
Can you confirm this was resolved with V3? Can I close?

**Comment by KevinJosephMorin** [comment]
I came up with a work around to the value not being there and have stuck with the old dll to avoid re-writing my code.  I am good with you closing this.  Kevin
